### ISSUE TITLE
Static VariantsManager?

### ISSUE THREAD

**Issue by CoolModder** [FortRise/FortRise#11]
I am trying to update the variants loading to avoid depreciated functions. It appears VariantsManager is set to static, preventing me from making variants in the new system.
Code:
`
     var IceArrow = FortRise.VariantManager.AddVariant(new CustomVariantInfo("StartWithIceArrows", VariantAtlas["StartWithIceArrows"],CustomVariantFlags.CanRandom | CustomVariantFlags.PerPlayer), false); 
` 
Error: An Object Reference Is Required For The Static Method "FortRise.VariantManager.AddVariant"

**Comment by Terria-K** [comment]
VariantManager is not static. You used the function wrong. Override the new function where you can have VariantManager as a parameter.
